version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  backend:
    image: python:3.11
    working_dir: /code
    volumes:
      - .:/code
    env_file: .env
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - minio
    ports:
      - "8000:8000"
  worker:
    image: python:3.11
    working_dir: /code
    volumes:
      - .:/code
    env_file: .env
    command: celery -A backend.worker.celery_app.celery_app worker -l info
    depends_on:
      - postgres
      - redis
      - rabbitmq
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
volumes:
  postgres_data:
  minio_data:
