name: Lint

on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff
      - name: Ruff
        run: ruff backend
      - name: Black
        run: black --check backend
  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        if: ${{ hashFiles('package.json') != '' }}
        run: npm ci
      - name: ESLint
        if: ${{ hashFiles('package.json') != '' }}
        run: npx eslint .
      - name: Prettier
        if: ${{ hashFiles('package.json') != '' }}
        run: npx prettier --check .
